# the killer tv - build the narration pack on Windows, with no API key.
#
#   powershell -ExecutionPolicy Bypass -File tools\generate-audio-sapi.ps1
#
# Uses the speech engine already in Windows, then leans on ffmpeg to drop the
# pitch and warm it up, because the stock voices are thin and far too chirpy for
# a narrator. Writes audio/<id>.mp3 and rewrites audio/manifest.json.
#
# Voices are whatever Windows has installed, usually en-US only. Add an en-GB
# voice under Settings, Time and Language, Speech if you want British.
#
# Keep this file ASCII only and saved with a BOM. PowerShell 5.1 reads a
# BOM-less file as ANSI and mangles any non-ASCII character in it, which shows
# up as a baffling parse error hundreds of lines from the real cause.

param(
  [string]$Voice   = 'Microsoft David Desktop',
  [int]   $Rate    = -2,      # SAPI rate, -10..10. Slower reads as more deliberate.
  [double]$Pitch   = 0.86,    # below 1 deepens. Applied by ffmpeg, not SAPI.
  [string]$Only    = '',      # comma separated line ids
  [switch]$Force
)

$ErrorActionPreference = 'Stop'
$root  = Split-Path -Parent $PSScriptRoot
$out   = Join-Path $root 'audio'
$tmp   = Join-Path $env:TEMP 'killer-tv-tts'
$lines = Get-Content (Join-Path $out '_lines.json') -Raw | ConvertFrom-Json

New-Item -ItemType Directory -Force $out, $tmp | Out-Null

Add-Type -AssemblyName System.Speech
$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
try { $synth.SelectVoice($Voice) } catch {
  Write-Warning "voice '$Voice' not found; using the default"
}
$synth.Rate = $Rate

$wanted = @()
if ($Only) { $wanted = $Only.Split(',') | ForEach-Object { $_.Trim() } }

$made = 0; $skipped = 0; $failed = 0
foreach ($p in $lines.PSObject.Properties) {
  $id   = $p.Name
  $text = $p.Value
  if ($wanted.Count -and $wanted -notcontains $id) { continue }

  $mp3 = Join-Path $out "$id.mp3"
  if ((Test-Path $mp3) -and -not $Force) { $skipped++; continue }

  $wav = Join-Path $tmp "$id.wav"
  try {
    $synth.SetOutputToWaveFile($wav)
    $synth.Speak($text)
    $synth.SetOutputToNull()

    # asetrate drops pitch and speed together; atempo puts the speed back, so it
    # ends up deeper at the original pace. Then a gentle low pass to take the
    # edge off, and a loudness pass so every clip sits at the same level.
    $tempo  = [math]::Round(1.0 / $Pitch, 4)
    $filter = "asetrate=22050*$Pitch,aresample=22050,atempo=$tempo,lowpass=f=6500,loudnorm=I=-17:TP=-2"

    & ffmpeg -y -loglevel error -i $wav -af $filter -ar 22050 -ac 1 -b:a 64k $mp3
    if ($LASTEXITCODE -ne 0) { throw "ffmpeg exit $LASTEXITCODE" }

    $kb = [math]::Round((Get-Item $mp3).Length / 1KB)
    Write-Host ("  ok  {0,-22} {1,4} kB" -f $id, $kb)
    $made++
  } catch {
    Write-Warning "  $id : $_"
    $failed++
  } finally {
    if (Test-Path $wav) { Remove-Item $wav -Force }
  }
}

$synth.Dispose()

$present = @($lines.PSObject.Properties.Name | Where-Object { Test-Path (Join-Path $out "$_.mp3") })
[ordered]@{
  note    = 'Generated by tools/generate-audio-sapi.ps1 from the Windows speech engine.'
  format  = 'mp3'
  voice   = $Voice
  lines   = $present
} | ConvertTo-Json -Depth 3 | Set-Content (Join-Path $out 'manifest.json') -Encoding utf8

# wrap in @() first: .Count on a PSObject property collection maps over the
# members instead of counting them, and you get a row of 1s
$total = @($lines.PSObject.Properties).Count
Write-Host ""
Write-Host "$made written, $skipped already there, $failed failed"
Write-Host "manifest lists $($present.Count) of $total lines"
