#!/usr/bin/env node
/* the killer tv — build the whole audio pack in one go.
 *
 *   set GOOGLE_TTS_KEY=...        (Windows cmd)
 *   $env:GOOGLE_TTS_KEY="..."     (PowerShell)
 *   export GOOGLE_TTS_KEY=...     (bash)
 *
 *   node tools/generate-audio.js
 *
 * Writes one MP3 per line into /audio and then rewrites audio/manifest.json to
 * match whatever is actually on disk. Existing files are left alone unless you
 * pass --force, so you can hand-record a few lines and let this fill the gaps.
 *
 * Options
 *   --force            regenerate files that already exist
 *   --voice <name>     default en-GB-Chirp3-HD-Charon
 *   --rate <number>    default 0.88
 *   --pitch <number>   default -4.0  (ignored by Chirp3-HD voices)
 *   --only <a,b,c>     just these line ids
 *   --manifest-only    don't call the API, just rebuild manifest.json
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'audio');

/* ---- read the script out of js/lines.js without importing the browser file ---- */
function loadLines() {
  const src = fs.readFileSync(path.join(ROOT, 'js', 'lines.js'), 'utf8');
  const sandbox = {};
  const body = src.replace(/^const LINES/m, 'sandbox.LINES').replace(/^const LINE_IDS[\s\S]*$/m, '');
  new Function('sandbox', body)(sandbox);
  return sandbox.LINES;
}

function arg(name, fallback) {
  const i = process.argv.indexOf('--' + name);
  return i !== -1 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
}
const has = (name) => process.argv.includes('--' + name);

const KEY = process.env.GOOGLE_TTS_KEY || '';
const VOICE = arg('voice', 'en-GB-Chirp3-HD-Charon');
const RATE = Number(arg('rate', '0.88'));
const PITCH = Number(arg('pitch', '-4.0'));
const FORCE = has('force');
const ONLY = arg('only', '');

function writeManifest(lines) {
  const present = Object.keys(lines).filter((id) => fs.existsSync(path.join(OUT, id + '.mp3')));
  fs.writeFileSync(
    path.join(OUT, 'manifest.json'),
    JSON.stringify({
      note: 'Generated by tools/generate-audio.js. Lists the line ids that exist as MP3s here.',
      format: 'mp3',
      voice: VOICE,
      lines: present,
    }, null, 2) + '\n'
  );
  return present.length;
}

async function synth(text) {
  const audioConfig = { audioEncoding: 'MP3', speakingRate: RATE };
  if (!/chirp/i.test(VOICE)) audioConfig.pitch = PITCH;

  const res = await fetch(
    'https://texttospeech.googleapis.com/v1/text:synthesize?key=' + encodeURIComponent(KEY),
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        input: { text },
        voice: { languageCode: VOICE.slice(0, 5), name: VOICE },
        audioConfig,
      }),
    }
  );
  if (!res.ok) throw new Error(res.status + ' ' + (await res.text()).slice(0, 300));
  const json = await res.json();
  if (!json.audioContent) throw new Error('no audio in response');
  return Buffer.from(json.audioContent, 'base64');
}

async function main() {
  const lines = loadLines();
  fs.mkdirSync(OUT, { recursive: true });

  if (has('manifest-only')) {
    console.log('manifest rewritten — ' + writeManifest(lines) + ' file(s) found');
    return;
  }

  if (!KEY) {
    console.error('GOOGLE_TTS_KEY is not set. See AUDIO.md.');
    process.exit(1);
  }

  let ids = Object.keys(lines);
  if (ONLY) {
    const wanted = ONLY.split(',').map((s) => s.trim());
    ids = ids.filter((id) => wanted.includes(id));
  }

  console.log('voice ' + VOICE + ' · rate ' + RATE + (/chirp/i.test(VOICE) ? '' : ' · pitch ' + PITCH));
  console.log(ids.length + ' line(s) to consider\n');

  let made = 0, skipped = 0, failed = 0;
  for (const id of ids) {
    const file = path.join(OUT, id + '.mp3');
    if (!FORCE && fs.existsSync(file)) { skipped++; continue; }
    try {
      const buf = await synth(lines[id]);
      fs.writeFileSync(file, buf);
      made++;
      console.log('  ✓ ' + id + '.mp3  (' + Math.round(buf.length / 1024) + ' kB)');
    } catch (err) {
      failed++;
      console.error('  ✗ ' + id + ' — ' + err.message);
    }
    await new Promise((r) => setTimeout(r, 120));   // be polite
  }

  const total = writeManifest(lines);
  console.log('\n' + made + ' written, ' + skipped + ' already there, ' + failed + ' failed');
  console.log('manifest lists ' + total + ' of ' + Object.keys(lines).length + ' lines');
}

main().catch((e) => { console.error(e); process.exit(1); });
